<?php

declare(strict_types=1);

namespace Config;

/**
 * Registry of domain apps registered in this hub.
 * Generated by ci4-kickstart on 2026-07-26 20:56:07.
 *
 * Use this to re-register domain apps after a fresh migrate+seed cycle
 * without needing the domain apps to be running.
 */
class DomainAppsRegistry
{
    /**
     * @var array<string, array{name: string, code: string, app_id: int}>
     */
    public const DOMAINS = [
        'cms' => [
            'name'   => 'teatromuseo teatromuseo-cms-domain',
            'code'   => 'cms',
            'app_id' => 2,
        ],
        'catalog' => [
            'name'   => 'teatromuseo teatromuseo-catalog-domain',
            'code'   => 'catalog',
            'app_id' => 5,
        ],
        'event' => [
            'name'   => 'teatromuseo teatromuseo-event-domain',
            'code'   => 'event',
            'app_id' => 6,
        ],
    ];
}
