<?php

declare(strict_types=1);

namespace Config;

/**
 * Registry of domain apps registered in this hub.
 * Generated by ci4-kickstart on 2026-06-11 02:29:29.
 *
 * Use this to re-register domain apps after a fresh migrate+seed cycle
 * without needing the domain apps to be running.
 */
class DomainAppsRegistry
{
    /**
     * @var array<string, array{name: string, code: string, app_id: int}>
     */
    public const DOMAINS = [
        'cms' => [
            'name'   => 'ci4-website-builder ci4-website-builder-domain',
            'code'   => 'cms',
            'app_id' => 3,
        ],
    ];
}
